# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f5c12ce60ff0a98665b945d81529a5a1cd225b1925d719b43dabcd2913ca7d84823a5b840aec3cb286d606fab3a13bd6a91fc87f323e83d39212b60788b5230

test:
  secret_key_base: 914219a042ad3b3cdbc0a638c88c51b40c61c8a8bd8e1b954ccafa6069a75dc3b22edd3b80b63984b7ba9ea60777e66260811076ef88b72ed79047c720a78334

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
